[package]
name = "rust-pomo-discord"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
discord-rich-presence = "0.2"
notify-rust = "4"
rodio = "0.17"
reqwest = { version = "0.11", features = ["blocking"] }
