name: Release

on:
  push:
    tags:
      - 'v*' # سيعمل الأكشن عندما ترفع Tag يبدأ بحرف v

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: pomo-linux
            asset_name: pomo-linux.tar.gz
          - os: windows-latest
            artifact_name: rust-pomo-discord.exe
            asset_name: pomo-windows.zip
          - os: macos-latest
            artifact_name: rust-pomo-discord
            asset_name: pomo-macos.tar.gz

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Package Assets (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/release
          tar -czf ../../${{ matrix.asset_name }} ${{ matrix.artifact_name }}

      - name: Package Assets (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/release
          compress-archive rust-pomo-discord.exe ../../${{ matrix.asset_name }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
